# Generated by Django 5.1.1 on 2024-09-15 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tag name')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Task name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('To do', 'Todo'), ('In progress', 'In Progress'), ('Review', 'Review'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='To do', max_length=20, verbose_name='Task status')),
                ('tags', models.ManyToManyField(related_name='tasks', to='tasks.tag', verbose_name='Tags')),
                ('users', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
